In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("c:/python_projects/data.csv")

In [3]:
df.head(50)

atmid              date                    problemname  \
0    PAYTM003  2021-04-08 20:41  BREAK DOWN/SOFTWARE CORRUPTED   
1    PAYTM003  2021-04-08 20:41  BREAK DOWN/SOFTWARE CORRUPTED   
2   PAYTM006   2021-04-03 11:46                 BREAK DOWN/EPP   
3   PAYTM006   2021-04-03 19:52                 BREAK DOWN/EPP   
4    PAYTM011  2021-04-05 20:24  BREAK DOWN/SOFTWARE CORRUPTED   
5    PAYTM011   2021-04-07 9:15  BREAK DOWN/SOFTWARE CORRUPTED   
6    PAYTM027  2021-04-14 10:05   BREAK DOWN/DISPENSER FAILURE   
7    PAYTM027  2021-04-15 20:40   BREAK DOWN/DISPENSER FAILURE   
8    PAYTM028  2021-04-16 11:23   BREAK DOWN/DISPENSER FAILURE   
9    PAYTM028  2021-04-17 17:08   BREAK DOWN/DISPENSER FAILURE   
10   PAYTM028  2021-04-21 17:58   BREAK DOWN/DISPENSER FAILURE   
11   PAYTM028  2021-04-23 10:20   BREAK DOWN/DISPENSER FAILURE   
12   PAYTM029  2021-04-19 14:00         BREAK DOWN/CARD READER   
13   PAYTM029  2021-04-20 17:58         BREAK DOWN/CARD READER   
14   PAYTM029  2021-04-22 20:09         BREAK DOWN/CARD READER   
15   PAYTM029  2021-04-22 20:09         BREAK DOWN/CARD READER   
16   PAYTM033  2021-04-19 12:54      BREAK DOWN/OUT OF SERVICE   
17   PAYTM033  2021-04-19 17:50      BREAK DOWN/OUT OF SERVICE   
18   PAYTM040   2021-04-11 9:53   BREAK DOWN/DISPENSER FAILURE   
19   PAYTM040  2021-04-13 16:21   BREAK DOWN/DISPENSER FAILURE   
20   PAYTM040   2021-04-14 9:58   BREAK DOWN/DISPENSER FAILURE   
21   PAYTM040  2021-04-17 13:41   BREAK DOWN/DISPENSER FAILURE   
22   PAYTM041  2021-04-11 11:47   BREAK DOWN/DISPENSER FAILURE   
23   PAYTM041  2021-04-15 20:40   BREAK DOWN/DISPENSER FAILURE   
24   PAYTM041  2021-04-20 15:46   BREAK DOWN/DISPENSER FAILURE   
25   PAYTM041  2021-04-22 16:40   BREAK DOWN/DISPENSER FAILURE   
26   PAYTM043  2021-04-03 15:32    OPERATIONAL/RECEIPT PRINTER   
27   PAYTM043  2021-04-04 13:17    OPERATIONAL/RECEIPT PRINTER   
28  PAYTM045   2021-04-09 16:32   BREAK DOWN/DISPENSER FAILURE   
29  PAYTM045   2021-04-10 12:26   BREAK DOWN/DISPENSER FAILURE   
30   PAYTM048  2021-04-10 10:47  BREAK DOWN/SOFTWARE CORRUPTED   
31   PAYTM048  2021-04-10 13:27  BREAK DOWN/SOFTWARE CORRUPTED   
32   PAYTM048  2021-04-15 12:46  BREAK DOWN/SOFTWARE CORRUPTED   
33   PAYTM048  2021-04-15 12:46  BREAK DOWN/SOFTWARE CORRUPTED   
34   PAYTM048  2021-04-27 10:22   BREAK DOWN/DISPENSER FAILURE   
35   PAYTM048  2021-04-27 12:15   BREAK DOWN/DISPENSER FAILURE   
36   PAYTM050  2021-04-10 11:21         BREAK DOWN/CARD READER   
37   PAYTM050  2021-04-12 16:47         BREAK DOWN/CARD READER   
38   PAYTM050  2021-04-13 13:21         BREAK DOWN/CARD READER   
39   PAYTM050  2021-04-13 13:21         BREAK DOWN/CARD READER   
40   PAYTM058  2021-04-08 17:30  BREAK DOWN/SOFTWARE CORRUPTED   
41   PAYTM058  2021-04-10 18:51  BREAK DOWN/SOFTWARE CORRUPTED   
42   PAYTM058  2021-04-21 12:27   BREAK DOWN/DISPENSER FAILURE   
43   PAYTM058  2021-04-28 16:36   BREAK DOWN/DISPENSER FAILURE   
44   PAYTM058  2021-04-30 15:36   BREAK DOWN/DISPENSER FAILURE   
45   PAYTM058  2021-05-01 20:25   BREAK DOWN/DISPENSER FAILURE   
46   PAYTM059  2021-04-16 16:47      BREAK DOWN/OUT OF SERVICE   
47   PAYTM059  2021-04-17 13:11      BREAK DOWN/OUT OF SERVICE   
48   PAYTM059  2021-04-17 13:11      BREAK DOWN/OUT OF SERVICE   
49   PAYTM059  2021-04-17 15:25      BREAK DOWN/OUT OF SERVICE   

                  mode                                            eventcd  \
0    SLM_DOCKET_CLOSED          BREAK DOWN/SOFTWARE CORRUPTED/HDD Machine   
1     PART_REPL_CLOSED                               FOC-HTNS-S5693000045   
2   SLM_DOCKET_CREATED            BREAK DOWN/EPP/EPP - Encrypting PIN Pad   
3    SLM_DOCKET_CLOSED            BREAK DOWN/EPP/EPP - Encrypting PIN Pad   
4   SLM_DOCKET_CREATED  BREAK DOWN/SOFTWARE CORRUPTED/Ghost/Operating ...   
5    SLM_DOCKET_CLOSED  BREAK DOWN/SOFTWARE CORRUPTED/Ghost/Operating ...   
6   SLM_DOCKET_CREATED  BREAK DOWN/DISPENSER FAILURE/Reject Cassette Full   
7    SLM_DOCKET_CLOSED  B

In [9]:
eventcd=dict.fromkeys(df['eventcd'].unique())

In [10]:
len(eventcd)

2155

In [70]:
array=[(1,2),(2,3)]

In [73]:
f=[deg for (n,deg) in list(array)]

In [74]:
f

[2, 3]

# train.py

## Function: load data monti (dataset,testing=False)

In [1]:
import mat73
import numpy as np

In [2]:
M=mat73.loadmat("c:/my_projects-main/gcmc/data/douban/training_test_dataset.mat",'M')
Otraining=mat73.loadmat("c:/my_projects-main/gcmc/data/douban/training_test_dataset.mat",'Otraining')
Otest=mat73.loadmat("c:/my_projects-main/gcmc/data/douban/training_test_dataset.mat",'Otest')

In [3]:
M.keys()

dict_keys(['M', 'Otest', 'Otraining', 'W_users'])

In [3]:
M

{'M': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 5., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'Otest': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'Otraining': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'W_users': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
       

In [4]:
num_users=M['M'].shape[0]
print(num_users)
num_items=M['M'].shape[1]
print(num_items)

3000
3000


In [5]:
M['Otest'][0].tolist()

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [6]:
M['Otest'].shape

(3000, 3000)

In [5]:
u_features=M['W_users'] # user id X features...(3000X3000)

In [6]:
u_features.shape,u_features[4,109]

((3000, 3000), 0.0)

In [6]:
v_features=np.eye(M['M'].shape[1]) #initializing identity matrix for v_features of shape (3000X3000)

In [8]:
v_features

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [7]:
u_nodes_ratings = np.where(M['M'])[0] #which user given rating ...
v_nodes_ratings = np.where(M['M'])[1] #which movies got rating...

In [10]:
u_nodes_ratings

array([   0,    0,    0, ..., 2999, 2999, 2999], dtype=int64)

In [13]:
u_nodes_ratings.shape

(136891,)

In [12]:
v_nodes_ratings.tolist()

[22,
 31,
 81,
 104,
 119,
 170,
 192,
 249,
 269,
 335,
 410,
 483,
 491,
 553,
 581,
 599,
 616,
 622,
 627,
 631,
 632,
 636,
 701,
 705,
 715,
 721,
 807,
 823,
 866,
 886,
 933,
 975,
 986,
 987,
 991,
 1060,
 1076,
 1080,
 1089,
 1177,
 1178,
 1184,
 1191,
 1231,
 1259,
 1302,
 1324,
 1387,
 1391,
 1395,
 1494,
 1617,
 1705,
 1706,
 1738,
 1740,
 1769,
 1813,
 1893,
 2036,
 2104,
 2201,
 2232,
 2314,
 2325,
 2361,
 2403,
 2833,
 2859,
 2983,
 2984,
 1,
 4,
 84,
 164,
 203,
 248,
 255,
 300,
 357,
 392,
 426,
 437,
 440,
 583,
 606,
 656,
 709,
 873,
 956,
 997,
 1159,
 1165,
 1181,
 1232,
 1455,
 1501,
 1585,
 1626,
 1733,
 1826,
 1945,
 1971,
 2080,
 2184,
 2249,
 2329,
 2338,
 2547,
 2639,
 2739,
 2763,
 2866,
 4,
 14,
 40,
 65,
 67,
 79,
 145,
 163,
 202,
 257,
 265,
 296,
 323,
 348,
 364,
 390,
 408,
 413,
 458,
 510,
 551,
 582,
 610,
 645,
 683,
 769,
 831,
 835,
 846,
 887,
 920,
 955,
 1038,
 1046,
 1138,
 1156,
 1195,
 1205,
 1296,
 1497,
 1517,
 1520,
 1562,
 1602,
 16

In [14]:
v_nodes_ratings.shape

(136891,)

In [8]:
ratings = M['M'][np.where(M['M'])] #rating given for each movie id by each user id...

In [10]:
ratings

array([4., 2., 1., ..., 4., 3., 3.])

In [17]:
ratings.shape

(136891,)

In [9]:
u_nodes_ratings, v_nodes_ratings = u_nodes_ratings.astype(np.int64), v_nodes_ratings.astype(np.int32)
ratings = ratings.astype(np.float64)

In [19]:
u_nodes_ratings.shape,v_nodes_ratings.shape,ratings.shape

((136891,), (136891,), (136891,))

In [10]:
u_nodes = u_nodes_ratings
v_nodes = v_nodes_ratings

print('number of users = ', len(set(u_nodes)))
print('number of item = ', len(set(v_nodes)))

number of users =  2999
number of item =  3000


In [21]:
u_nodes,v_nodes,ratings

(array([   0,    0,    0, ..., 2999, 2999, 2999], dtype=int64),
 array([  22,   31,   81, ..., 2210, 2341, 2469]),
 array([4., 2., 1., ..., 4., 3., 3.]))

In [22]:
u_nodes.shape

(136891,)

In [11]:
neutral_rating = -1
# assumes that ratings_train contains at least one example of every rating type
rating_dict = {r: i for i, r in enumerate(np.sort(np.unique(ratings)).tolist())}

In [12]:
rating_dict

{1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}

In [12]:
labels = np.full((num_users, num_items), neutral_rating, dtype=np.int32)

In [15]:
labels

array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [27]:
labels.shape

(3000, 3000)

In [13]:
labels[u_nodes, v_nodes] = np.array([rating_dict[r] for r in ratings])

In [16]:
labels

array([[-1, -1, -1, ..., -1, -1, -1],
       [-1,  4, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [29]:
labels[0].tolist()

[-1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 3,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 2,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 2,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -

In [14]:
for i in range(len(u_nodes)):
    assert(labels[u_nodes[i], v_nodes[i]] == rating_dict[ratings[i]])

labels = labels.reshape([-1]) # converting 3000X3000 matrix to 1-d array

In [18]:
labels,labels.shape 

(array([-1, -1, -1, ..., -1, -1, -1]), (9000000,))

In [15]:
# number of test and validation edges
num_train = np.where(Otraining['Otraining'])[0].shape[0] # sames as u_nodes but with 123202 rows... 
num_train

123202

In [16]:
num_train_temp = np.where(Otraining['Otraining'])[0]
num_train_temp

array([   0,    0,    0, ..., 2999, 2999, 2999], dtype=int64)

In [17]:
num_test = np.where(Otest['Otest'])[0].shape[0] #same as u_nodes but with 13689 rows...
num_test

13689

In [18]:
num_test_temp = np.where(Otest['Otest'])[0]
num_test_temp

array([   0,    0,    0, ..., 2999, 2999, 2999], dtype=int64)

In [19]:
num_val = int(np.ceil(num_train * 0.2))
num_val

24641

In [20]:
num_train = num_train - num_val
num_train

98561

In [21]:
#user id : movie id (rating given by a particular user for a particular movie or a set of movies)
pairs_nonzero_train = np.array([[u, v] for u, v in zip(np.where(Otraining['Otraining'])[0], np.where(Otraining['Otraining'])[1])])
print(pairs_nonzero_train)
# user id*number of items+movie id (for e.g. considering first row, 0*3000+22=22)
idx_nonzero_train = np.array([u * num_items + v for u, v in pairs_nonzero_train])
print(idx_nonzero_train)
print(len(idx_nonzero_train))

[[   0   22]
 [   0   31]
 [   0   81]
 ...
 [2999 2210]
 [2999 2341]
 [2999 2469]]
[     22      31      81 ... 8999210 8999341 8999469]
123202


In [22]:
pairs_nonzero_test = np.array([[u, v] for u, v in zip(np.where(Otest['Otest'])[0], np.where(Otest['Otest'])[1])])
print(pairs_nonzero_test)
idx_nonzero_test = np.array([u * num_items + v for u, v in pairs_nonzero_test])
print(idx_nonzero_test)
print(len(idx_nonzero_test))

[[   0  104]
 [   0  192]
 [   0  335]
 ...
 [2999 1390]
 [2999 1975]
 [2999 2128]]
[    104     192     335 ... 8998390 8998975 8999128]
13689


In [23]:
# Internally shuffle training set (before splitting off validation set)...
rand_idx = list(range(len(idx_nonzero_train)))
rand_idx

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [28]:
print(len(rand_idx))

123202


In [24]:
np.random.seed(42)
np.random.shuffle(rand_idx)

In [25]:
idx_nonzero_train = idx_nonzero_train[rand_idx]
print(idx_nonzero_train)
pairs_nonzero_train = pairs_nonzero_train[rand_idx]
print(pairs_nonzero_train)

[3207860  738658  936032 ...   53478 1034056 8898464]
[[1069  860]
 [ 246  658]
 [ 312   32]
 ...
 [  17 2478]
 [ 344 2056]
 [2966  464]]


In [26]:
idx_nonzero = np.concatenate([idx_nonzero_train, idx_nonzero_test], axis=0)
pairs_nonzero = np.concatenate([pairs_nonzero_train, pairs_nonzero_test], axis=0)

In [47]:
idx_nonzero.shape,pairs_nonzero.shape

((136891,), (136891, 2))

In [46]:
idx_nonzero

array([3207860,  738658,  936032, ..., 8998390, 8998975, 8999128],
      dtype=int64)

In [27]:
val_idx = idx_nonzero[0:num_val]
train_idx = idx_nonzero[num_val:num_train + num_val]
test_idx = idx_nonzero[num_train + num_val:]

In [49]:
val_idx,len(val_idx)

(array([3207860,  738658,  936032, ..., 7233601, 1735040, 2631585],
       dtype=int64),
 24641)

In [50]:
train_idx,len(val_idx)

(array([8134121, 4207664, 1732173, ...,   53478, 1034056, 8898464],
       dtype=int64),
 24641)

In [51]:
test_idx,len(val_idx)

(array([    104,     192,     335, ..., 8998390, 8998975, 8999128],
       dtype=int64),
 24641)

In [28]:
assert(len(test_idx) == num_test)

In [29]:
val_pairs_idx = pairs_nonzero[0:num_val]
train_pairs_idx = pairs_nonzero[num_val:num_train + num_val]
test_pairs_idx = pairs_nonzero[num_train + num_val:]

In [54]:
val_pairs_idx,val_pairs_idx.shape

(array([[1069,  860],
        [ 246,  658],
        [ 312,   32],
        ...,
        [2411,  601],
        [ 578, 1040],
        [ 877,  585]], dtype=int64),
 (24641, 2))

In [55]:
train_pairs_idx,train_pairs_idx.shape

(array([[2711, 1121],
        [1402, 1664],
        [ 577, 1173],
        ...,
        [  17, 2478],
        [ 344, 2056],
        [2966,  464]], dtype=int64),
 (98561, 2))

In [56]:
test_pairs_idx,test_pairs_idx.shape

(array([[   0,  104],
        [   0,  192],
        [   0,  335],
        ...,
        [2999, 1390],
        [2999, 1975],
        [2999, 2128]], dtype=int64),
 (13689, 2))

In [30]:
u_test_idx, v_test_idx = test_pairs_idx.transpose()
u_val_idx, v_val_idx = val_pairs_idx.transpose()
u_train_idx, v_train_idx = train_pairs_idx.transpose()

In [58]:
# create labels
u_test_idx,v_test_idx

(array([   0,    0,    0, ..., 2999, 2999, 2999], dtype=int64),
 array([ 104,  192,  335, ..., 1390, 1975, 2128], dtype=int64))

In [59]:
u_val_idx, v_val_idx

(array([1069,  246,  312, ..., 2411,  578,  877], dtype=int64),
 array([ 860,  658,   32, ...,  601, 1040,  585], dtype=int64))

In [60]:
u_train_idx,u_train_idx.shape, v_train_idx,v_train_idx.shape

(array([2711, 1402,  577, ...,   17,  344, 2966], dtype=int64),
 (98561,),
 array([1121, 1664, 1173, ..., 2478, 2056,  464], dtype=int64),
 (98561,))

In [31]:
train_labels = labels[train_idx]
val_labels = labels[val_idx]
test_labels = labels[test_idx]

In [62]:
train_labels,train_labels.shape

(array([4, 3, 2, ..., 4, 2, 3]), (98561,))

In [63]:
val_labels,val_labels.shape

(array([3, 3, 4, ..., 3, 3, 4]), (24641,))

In [64]:
test_labels,test_labels.shape

(array([2, 1, 0, ..., 3, 2, 2]), (13689,))

In [32]:
u_train_idx = np.hstack([u_train_idx, u_val_idx]) # for e.g. 0,0,0,1,1,1.....2999,2999 but excluding u_test_idx
v_train_idx = np.hstack([v_train_idx, v_val_idx]) # for e.g. 102,104.....2854,2957 but excluding v_test_idx
train_labels = np.hstack([train_labels, val_labels])# rating for the movies given by the user...
# for adjacency matrix construction
train_idx = np.hstack([train_idx, val_idx]) # user id*num_items+movie id

In [67]:
u_train_idx,u_train_idx.shape

(array([2711, 1402,  577, ..., 2411,  578,  877], dtype=int64), (147843,))

In [68]:
v_train_idx,v_train_idx.shape

(array([1121, 1664, 1173, ...,  601, 1040,  585], dtype=int64), (147843,))

In [69]:
train_labels,train_labels.shape

(array([4, 3, 2, ..., 3, 3, 4]), (147843,))

In [70]:
train_idx,train_idx.shape

(array([8134121, 4207664, 1732173, ..., 7233601, 1735040, 2631585],
       dtype=int64),
 (147843,))

In [33]:
# make training adjacency matrix
import scipy.sparse as sp
rating_mx_train = np.zeros(num_users * num_items, dtype=np.float32)

In [37]:
rating_mx_train,rating_mx_train.shape

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), (9000000,))

In [34]:
rating_mx_train[train_idx] = labels[train_idx].astype(np.float32) + 1.

In [41]:
rating_mx_train,rating_mx_train.shape

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), (9000000,))

In [75]:
rating_mx_train.tolist()

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 4.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [35]:
rating_mx_train = sp.csr_matrix(rating_mx_train.reshape(num_users, num_items)) #reshaping to 3000X3000 matrix...

In [36]:
rating_mx_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [37]:
rating_mx_train

<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 123202 stored elements in Compressed Sparse Row format>

In [38]:
class_values = np.sort(np.unique(ratings))

In [39]:
class_values

array([1., 2., 3., 4., 5.])

In [40]:
u_features = sp.csr_matrix(u_features)
print("User features shape: " + str(u_features.shape))

User features shape: (3000, 3000)


In [41]:
v_features = sp.csr_matrix(v_features)
print("Item features shape: " + str(v_features.shape))

Item features shape: (3000, 3000)


In [42]:
print('u_features' , u_features)
print('v_features' , v_features) 
print('adj_train' , rating_mx_train) #adj_train
print('train_labels ', train_labels)
print('train_u_indices' , u_train_idx) #train_u_indices
print('train_v_indices' , v_train_idx) #train_v_indices
print('val_labels' , val_labels)
print('val_u_indices' , u_val_idx) #val_u_indices
print('val_v_indices' , v_val_idx) #val_v_indices
print('test_labels' , test_labels)
print('test_u_indices' , u_test_idx) #test_u_indices
print('test_v_indices' , v_test_idx) #test_v_indices
print(class_values)

u_features   (4, 109)	1.0
  (4, 767)	1.0
  (4, 1518)	1.0
  (4, 1719)	1.0
  (4, 2206)	1.0
  (4, 2651)	1.0
  (4, 2938)	1.0
  (12, 900)	1.0
  (12, 1461)	1.0
  (12, 2420)	1.0
  (12, 2767)	1.0
  (13, 412)	1.0
  (17, 2247)	1.0
  (20, 1045)	1.0
  (22, 109)	1.0
  (26, 1671)	1.0
  (28, 2836)	1.0
  (30, 108)	1.0
  (30, 952)	1.0
  (30, 1373)	1.0
  (30, 1501)	1.0
  (32, 309)	1.0
  (32, 1218)	1.0
  (32, 1435)	1.0
  (32, 2889)	1.0
  :	:
  (2971, 1612)	1.0
  (2971, 2839)	1.0
  (2972, 2128)	1.0
  (2972, 2255)	1.0
  (2973, 1536)	1.0
  (2976, 183)	1.0
  (2976, 554)	1.0
  (2976, 700)	1.0
  (2976, 1009)	1.0
  (2976, 1376)	1.0
  (2976, 2142)	1.0
  (2976, 2430)	1.0
  (2976, 2458)	1.0
  (2976, 2674)	1.0
  (2977, 309)	1.0
  (2977, 981)	1.0
  (2983, 1541)	1.0
  (2984, 2500)	1.0
  (2989, 345)	1.0
  (2989, 1452)	1.0
  (2990, 876)	1.0
  (2991, 2271)	1.0
  (2998, 1260)	1.0
  (2998, 2381)	1.0
  (2998, 2675)	1.0
v_features   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
  (6, 6)	1.0
  (

## Func: normalize_features(feat)

### for u_features...

In [43]:
# Normalize the u_features...
degree = np.asarray(u_features.sum(1)).flatten()

In [44]:
degree,degree.shape

(array([0., 0., 0., ..., 0., 3., 0.]), (3000,))

In [45]:
# set zeros to inf to avoid dividing by zero
degree[degree == 0.] = np.inf

In [46]:
degree

array([inf, inf, inf, ..., inf,  3., inf])

In [47]:
degree_inv = 1. / degree

In [48]:
degree_inv_mat = sp.diags([degree_inv], [0])

In [49]:
degree_inv_mat.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.33333333,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [50]:
degree_inv_mat

<3000x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements (1 diagonals) in DIAgonal format>

In [51]:
feat_norm = degree_inv_mat.dot(u_features) #D-1*A

In [52]:
u_features_side=feat_norm

In [53]:
u_features_side

<3000x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 2690 stored elements in Compressed Sparse Row format>

In [ ]:
if feat_norm.nnz == 0:
    print('ERROR: normalized adjacency matrix has only zero entries!!!!!')

### for v_features...

In [54]:
# Normalize the v_features...
degree = np.asarray(v_features.sum(1)).flatten()

In [55]:
degree,degree.shape

(array([1., 1., 1., ..., 1., 1., 1.]), (3000,))

In [56]:
# set zeros to inf to avoid dividing by zero
degree[degree == 0.] = np.inf

In [58]:
degree

array([1., 1., 1., ..., 1., 1., 1.])

In [57]:
degree_inv = 1. / degree

In [58]:
degree_inv_mat = sp.diags([degree_inv], [0])

In [59]:
degree_inv_mat.toarray()

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [60]:
degree_inv_mat

<3000x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements (1 diagonals) in DIAgonal format>

In [61]:
feat_norm = degree_inv_mat.dot(v_features) #D-1*A

In [62]:
feat_norm

<3000x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements in Compressed Sparse Row format>

In [63]:
v_features_side=feat_norm

In [64]:
v_features_side

<3000x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements in Compressed Sparse Row format>

In [ ]:
if feat_norm.nnz == 0:
    print('ERROR: normalized adjacency matrix has only zero entries!!!!!')

## preprocess_user_item_features(u_features,v_features)

In [65]:
zero_csr_u = sp.csr_matrix((u_features.shape[0], v_features.shape[1]), dtype=u_features.dtype)
zero_csr_v = sp.csr_matrix((v_features.shape[0], u_features.shape[1]), dtype=v_features.dtype)

In [66]:
zero_csr_u.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [68]:
zero_csr_u

<3000x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [67]:
u_features = sp.hstack([u_features, zero_csr_u], format='csr') # normalized u_features and zero matrix
v_features = sp.hstack([zero_csr_v, v_features], format='csr') # normalized identity matrix and zero matrix

In [70]:
u_features.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [68]:
u_features

<3000x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 2690 stored elements in Compressed Sparse Row format>

In [69]:
u_features_side=u_features

In [70]:
v_features.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [71]:
v_features

<3000x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements in Compressed Sparse Row format>

In [72]:
v_features_side=v_features

In [73]:
v_features_side

<3000x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements in Compressed Sparse Row format>

In [74]:
u_features_side = np.array(u_features_side.todense(), dtype=np.float32)
v_features_side = np.array(v_features_side.todense(), dtype=np.float32)

In [75]:
u_features_side,u_features.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (3000, 6000))

In [76]:
v_features_side,v_features.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]], dtype=float32),
 (3000, 6000))

In [77]:
num_side_features = u_features_side.shape[1]

In [78]:
num_side_features

6000

In [79]:
id_csr_v = sp.identity(num_items, format='csr')
id_csr_u = sp.identity(num_users, format='csr')

In [80]:
id_csr_u

<3000x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements in Compressed Sparse Row format>

In [81]:
id_csr_v

<3000x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements in Compressed Sparse Row format>

### again preprocessing identity matrices...

In [82]:
zero_csr_u = sp.csr_matrix((id_csr_u.shape[0], id_csr_v.shape[1]), dtype=u_features.dtype)
zero_csr_v = sp.csr_matrix((id_csr_v.shape[0], id_csr_u.shape[1]), dtype=v_features.dtype)

In [83]:
zero_csr_u.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [84]:
zero_csr_u

<3000x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [203]:
u_features = sp.hstack([id_csr_u, zero_csr_u], format='csr')
v_features = sp.hstack([zero_csr_v,id_csr_v ], format='csr')

In [204]:
u_features #identity matrix and zero matrix

<3000x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements in Compressed Sparse Row format>

In [205]:
v_features #zero matrix and identity matrix

<3000x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements in Compressed Sparse Row format>

## Global Normalization...

In [88]:
adj_train=rating_mx_train
# Global Normalization...
support = []
support_t = []
adj_train_int = sp.csr_matrix(adj_train, dtype=np.int32)

In [136]:
adj_train_int.toarray()[0].tolist()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,


In [89]:
adj_train_int #user id X movie id with ratings...

<3000x3000 sparse matrix of type '<class 'numpy.int32'>'
	with 123202 stored elements in Compressed Sparse Row format>

In [90]:
for i in range(5):
    # build individual binary rating matrices (supports) for each rating
    support_unnormalized = sp.csr_matrix(adj_train_int == i + 1, dtype=np.float32)

In [91]:
support_unnormalized.toarray()[1].tolist()

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0

In [92]:
support_unnormalized

<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 25288 stored elements in Compressed Sparse Row format>

In [93]:
support_unnormalized_transpose = support_unnormalized.T
support.append(support_unnormalized)
support_t.append(support_unnormalized_transpose)

In [94]:
support

[<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
 	with 25288 stored elements in Compressed Sparse Row format>]

In [95]:
support_t

[<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
 	with 25288 stored elements in Compressed Sparse Column format>]

## Func: globally_normalize_bipartite_adjacency (adjacencies=support,verbose=False, symmetric=True)

### for support...

In [96]:
# degree_u and degree_v are row and column sums of adj+I
adjacencies=support
adj_tot = np.sum(adj for adj in adjacencies)
adj_tot

c:\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  This is separate from the ipykernel package so we can avoid doing imports until


<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 25288 stored elements in Compressed Sparse Row format>

In [97]:
degree_u = np.asarray(adj_tot.sum(1)).flatten()
degree_u,degree_u.shape

(array([ 4., 10., 10., ...,  0.,  2.,  8.], dtype=float32), (3000,))

In [98]:
degree_v = np.asarray(adj_tot.sum(0)).flatten()
degree_v,degree_v.shape

(array([35., 21.,  8., ...,  9.,  9.,  0.], dtype=float32), (3000,))

In [99]:
# set zeros to inf to avoid dividing by zero
degree_u[degree_u == 0.] = np.inf
degree_v[degree_v == 0.] = np.inf

In [100]:
degree_u

array([ 4., 10., 10., ..., inf,  2.,  8.], dtype=float32)

In [101]:
degree_v

array([35., 21.,  8., ...,  9.,  9., inf], dtype=float32)

In [102]:
degree_u_inv_sqrt = 1. / np.sqrt(degree_u)

In [103]:
degree_u_inv_sqrt

array([0.5       , 0.31622776, 0.31622776, ..., 0.        , 0.70710677,
       0.35355338], dtype=float32)

In [104]:
degree_v_inv_sqrt = 1. / np.sqrt(degree_v)
degree_v_inv_sqrt

array([0.16903085, 0.21821788, 0.35355338, ..., 0.33333334, 0.33333334,
       0.        ], dtype=float32)

In [105]:
degree_u_inv_sqrt_mat = sp.diags([degree_u_inv_sqrt], [0])

In [106]:
degree_u_inv_sqrt_mat.toarray()

array([[0.5       , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.31622776, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.31622776, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.70710677,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.35355338]], dtype=float32)

In [107]:
degree_u_inv_sqrt_mat

<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 3000 stored elements (1 diagonals) in DIAgonal format>

In [108]:
degree_v_inv_sqrt_mat = sp.diags([degree_v_inv_sqrt], [0])
degree_v_inv_sqrt_mat

<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 3000 stored elements (1 diagonals) in DIAgonal format>

In [109]:
degree_u_inv = degree_u_inv_sqrt_mat.dot(degree_u_inv_sqrt_mat) #D-0.5*D-0.5 = D-1

In [110]:
degree_u_inv

<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 2783 stored elements in Compressed Sparse Row format>

In [111]:
adj_norm = [degree_u_inv_sqrt_mat.dot(adj).dot(degree_v_inv_sqrt_mat) for adj in adjacencies]

In [112]:
support=adj_norm

In [113]:
support

[<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
 	with 25288 stored elements in Compressed Sparse Row format>]

### for support_t

In [114]:
# degree_u and degree_v are row and column sums of adj+I
adjacencies=support_t
adj_tot = np.sum(adj for adj in adjacencies)
adj_tot

c:\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  This is separate from the ipykernel package so we can avoid doing imports until


<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 25288 stored elements in Compressed Sparse Column format>

In [115]:
degree_u = np.asarray(adj_tot.sum(1)).flatten() # one movie got rating from 35 users...
degree_u,degree_u.shape

(array([35., 21.,  8., ...,  9.,  9.,  0.], dtype=float32), (3000,))

In [116]:
degree_v = np.asarray(adj_tot.sum(0)).flatten() # one user rated for 4 movies...
degree_v,degree_v.shape

(array([ 4., 10., 10., ...,  0.,  2.,  8.], dtype=float32), (3000,))

In [117]:
# set zeros to inf to avoid dividing by zero
degree_u[degree_u == 0.] = np.inf
degree_v[degree_v == 0.] = np.inf

In [118]:
degree_u

array([35., 21.,  8., ...,  9.,  9., inf], dtype=float32)

In [168]:
degree_v

array([ 4., 10., 10., ..., inf,  2.,  8.], dtype=float32)

In [119]:
degree_u_inv_sqrt = 1. / np.sqrt(degree_u)

In [120]:
degree_u_inv_sqrt

array([0.16903085, 0.21821788, 0.35355338, ..., 0.33333334, 0.33333334,
       0.        ], dtype=float32)

In [121]:
degree_v_inv_sqrt = 1. / np.sqrt(degree_v)
degree_v_inv_sqrt

array([0.5       , 0.31622776, 0.31622776, ..., 0.        , 0.70710677,
       0.35355338], dtype=float32)

In [122]:
degree_u_inv_sqrt_mat = sp.diags([degree_u_inv_sqrt], [0])

In [123]:
degree_u_inv_sqrt_mat

<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 3000 stored elements (1 diagonals) in DIAgonal format>

In [124]:
degree_v_inv_sqrt_mat = sp.diags([degree_v_inv_sqrt], [0])
degree_v_inv_sqrt_mat

<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 3000 stored elements (1 diagonals) in DIAgonal format>

In [125]:
degree_u_inv = degree_u_inv_sqrt_mat.dot(degree_u_inv_sqrt_mat)

In [126]:
degree_u_inv

<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
	with 2827 stored elements in Compressed Sparse Row format>

In [127]:
adj_norm = [degree_u_inv_sqrt_mat.dot(adj).dot(degree_v_inv_sqrt_mat) for adj in adjacencies]

In [128]:
support_t=adj_norm

In [129]:
support_t

[<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
 	with 25288 stored elements in Compressed Sparse Row format>]

In [130]:
support.append(sp.identity(u_features.shape[0], format='csr'))

In [131]:
support

[<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
 	with 25288 stored elements in Compressed Sparse Row format>,
 <3000x3000 sparse matrix of type '<class 'numpy.float64'>'
 	with 3000 stored elements in Compressed Sparse Row format>]

In [132]:
support_t.append(sp.identity(v_features.shape[0], format='csr'))

In [133]:
support_t

[<3000x3000 sparse matrix of type '<class 'numpy.float32'>'
 	with 25288 stored elements in Compressed Sparse Row format>,
 <3000x3000 sparse matrix of type '<class 'numpy.float64'>'
 	with 3000 stored elements in Compressed Sparse Row format>]

In [134]:
num_support = len(support)
num_support

2

In [135]:
support = sp.hstack(support, format='csr')

In [136]:
support.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [137]:
support #D-0.5*A*D-0.5*I

<3000x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 28288 stored elements in Compressed Sparse Row format>

In [138]:
support_t = sp.hstack(support_t, format='csr')

In [139]:
support_t.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [140]:
support_t #D-0.5*A*D-0.5*I

<3000x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 28288 stored elements in Compressed Sparse Row format>

## Collect all user and item nodes for test set

In [1]:
test_u_indices=u_test_idx
test_v_indices=v_test_idx
test_u = list(set(test_u_indices))
test_v = list(set(test_v_indices))
test_u_dict = {n: i for i, n in enumerate(test_u)}
test_v_dict = {n: i for i, n in enumerate(test_v)}

NameError: name 'u_test_idx' is not defined

In [192]:
test_v_dict

{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 6: 6,
 7: 7,
 8: 8,
 9: 9,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 16: 16,
 17: 17,
 18: 18,
 19: 19,
 20: 20,
 21: 21,
 22: 22,
 23: 23,
 24: 24,
 25: 25,
 26: 26,
 27: 27,
 28: 28,
 29: 29,
 30: 30,
 31: 31,
 32: 32,
 33: 33,
 34: 34,
 35: 35,
 36: 36,
 37: 37,
 38: 38,
 39: 39,
 40: 40,
 41: 41,
 42: 42,
 43: 43,
 44: 44,
 45: 45,
 46: 46,
 47: 47,
 48: 48,
 49: 49,
 50: 50,
 51: 51,
 52: 52,
 53: 53,
 54: 54,
 55: 55,
 56: 56,
 57: 57,
 58: 58,
 59: 59,
 60: 60,
 61: 61,
 62: 62,
 63: 63,
 64: 64,
 65: 65,
 66: 66,
 67: 67,
 68: 68,
 69: 69,
 70: 70,
 71: 71,
 72: 72,
 73: 73,
 74: 74,
 75: 75,
 76: 76,
 77: 77,
 78: 78,
 79: 79,
 80: 80,
 81: 81,
 82: 82,
 83: 83,
 84: 84,
 85: 85,
 86: 86,
 87: 87,
 88: 88,
 89: 89,
 90: 90,
 91: 91,
 92: 92,
 93: 93,
 94: 94,
 95: 95,
 96: 96,
 97: 97,
 98: 98,
 99: 99,
 100: 100,
 101: 101,
 102: 102,
 103: 103,
 104: 104,
 105: 105,
 106: 106,
 107: 107,
 108: 108,
 109: 109,
 110: 110,

In [142]:
# getting the values(indices) from the dictionary of users:indices 
test_u_indices = np.array([test_u_dict[o] for o in test_u_indices])
test_v_indices = np.array([test_v_dict[o] for o in test_v_indices])

In [143]:
test_u_indices

array([   0,    0,    0, ..., 2881, 2881, 2881])

In [146]:
np.array(test_u)

array([   0,    1,    2, ..., 2996, 2998, 2999], dtype=int64)

In [144]:
test_support = support[np.array(test_u)]
test_support_t = support_t[np.array(test_v)]

In [149]:
test_support.toarray(),test_support.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 (2882, 6000))

In [150]:
test_support

<2882x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 27706 stored elements in Compressed Sparse Row format>

In [151]:
test_support_t.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [152]:
test_support_t

<2916x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 27637 stored elements in Compressed Sparse Row format>

## Collect all user and item nodes for validation set

In [153]:
val_u_indices=u_val_idx
val_v_indices=v_val_idx
val_u = list(set(val_u_indices))
val_v = list(set(val_v_indices))
val_u_dict = {n: i for i, n in enumerate(val_u)}
val_v_dict = {n: i for i, n in enumerate(val_v)}

val_u_indices = np.array([val_u_dict[o] for o in val_u_indices])
val_v_indices = np.array([val_v_dict[o] for o in val_v_indices])

val_support = support[np.array(val_u)]
val_support_t = support_t[np.array(val_v)]

In [154]:
val_support.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [155]:
val_support

<2977x6000 sparse matrix of type '<class 'numpy.float64'>'
	with 28201 stored elements in Compressed Sparse Row format>

## Collect all user and item nodes for train set

In [184]:
train_u_indices=u_train_idx
train_v_indices=v_train_idx
train_u = list(set(train_u_indices))
train_v = list(set(train_v_indices))
train_u_dict = {n: i for i, n in enumerate(train_u)}
train_v_dict = {n: i for i, n in enumerate(train_v)}

train_u_indices = np.array([train_u_dict[o] for o in train_u_indices])
train_v_indices = np.array([train_v_dict[o] for o in train_v_indices])

train_support = support[np.array(train_u)]
train_support_t = support_t[np.array(train_v)]

## features as side info

In [162]:
test_u_features_side = u_features_side[np.array(test_u)]
test_v_features_side = v_features_side[np.array(test_v)]

val_u_features_side = u_features_side[np.array(val_u)]
val_v_features_side = v_features_side[np.array(val_v)]

train_u_features_side = u_features_side[np.array(train_u)]
train_v_features_side = v_features_side[np.array(train_v)]

In [164]:
test_u_features_side,test_u_features_side.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (2882, 6000))

In [166]:
test_v_features_side,test_v_features_side.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.]], dtype=float32),
 (2916, 6000))

In [167]:
train_u_features_side,train_u_features_side.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (2999, 6000))

In [169]:
train_v_features_side,train_v_features_side.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]], dtype=float32),
 (3000, 6000))

## Func: sparse_to_tuple(sparse_mx=test_support)

### for test_support...

In [171]:
if not sp.isspmatrix_coo(test_support):
    sparse_mx = test_support.tocoo()
    coords = np.vstack((sparse_mx.row, sparse_mx.col)).transpose()
    values = sparse_mx.data
    shape = sparse_mx.shape
print('sparse_mx ', sparse_mx)
print('coords' , coords)
print('values' , values)
print('shape' , shape)

sparse_mx    (0, 269)	0.11470786482095718
  (0, 1060)	0.1178511381149292
  (0, 1231)	0.22360679507255554
  (0, 2859)	0.22360679507255554
  (0, 3000)	1.0
  (1, 164)	0.05976143479347229
  (1, 300)	0.06324555724859238
  (1, 392)	0.05773502588272095
  (1, 426)	0.08451542258262634
  (1, 606)	0.15811388194561005
  (1, 709)	0.08770579844713211
  (1, 1501)	0.09128709137439728
  (1, 2080)	0.08164965361356735
  (1, 2639)	0.11180339753627777
  (1, 2763)	0.11952286958694458
  (1, 3001)	1.0
  (2, 40)	0.041522737592458725
  (2, 323)	0.0690065547823906
  (2, 390)	0.09534625709056854
  (2, 458)	0.06085806339979172
  (2, 683)	0.10000000149011612
  (2, 1562)	0.09128709137439728
  (2, 1602)	0.08451542258262634
  (2, 1640)	0.18257418274879456
  (2, 2065)	0.0690065547823906
  :	:
  (2877, 644)	0.07881104201078415
  (2877, 766)	0.15430335700511932
  (2877, 2913)	0.18898224830627441
  (2877, 5994)	1.0
  (2878, 517)	0.14433756470680237
  (2878, 656)	0.5
  (2878, 698)	0.07624928653240204
  (2878, 958)	0.144337

In [172]:
test_support= coords,values,shape

In [173]:
test_support

(array([[   0,  269],
        [   0, 1060],
        [   0, 1231],
        ...,
        [2881, 1079],
        [2881, 1784],
        [2881, 5999]], dtype=int32),
 array([0.11470786, 0.11785114, 0.2236068 , ..., 0.10206207, 0.07905694,
        1.        ]),
 (2882, 6000))

### for test_support_t...

In [174]:
if not sp.isspmatrix_coo(test_support_t):
    sparse_mx = test_support_t.tocoo()
    coords = np.vstack((sparse_mx.row, sparse_mx.col)).transpose()
    values = sparse_mx.data
    shape = sparse_mx.shape
print('sparse_mx ', sparse_mx)
print('coords' , coords)
print('values' , values)
print('shape' , shape)

sparse_mx    (0, 40)	0.06388765573501587
  (0, 214)	0.06900654733181
  (0, 258)	0.031388238072395325
  (0, 296)	0.04879499971866608
  (0, 433)	0.04879499971866608
  (0, 741)	0.07559289038181305
  (0, 823)	0.04225771129131317
  (0, 885)	0.039840955287218094
  (0, 920)	0.04517539218068123
  (0, 969)	0.08451542258262634
  (0, 1067)	0.04688072204589844
  (0, 1071)	0.05096471682190895
  (0, 1160)	0.033806171268224716
  (0, 1509)	0.07559289038181305
  (0, 1544)	0.11952285468578339
  (0, 1561)	0.07559289038181305
  (0, 1608)	0.06388765573501587
  (0, 1625)	0.05096471682190895
  (0, 1899)	0.05976142734289169
  (0, 1914)	0.04225771129131317
  (0, 1923)	0.03688555210828781
  (0, 1931)	0.06900654733181
  (0, 2034)	0.038778334856033325
  (0, 2118)	0.07559289038181305
  (0, 2162)	0.023904573172330856
  :	:
  (2911, 618)	0.19999998807907104
  (2911, 789)	0.14907120168209076
  (2911, 1525)	0.10846523195505142
  (2911, 2725)	0.11952285468578339
  (2911, 5994)	1.0
  (2912, 1129)	0.15430334210395813
  (

In [175]:
test_support_t=coords,values,shape

In [176]:
test_support_t

(array([[   0,   40],
        [   0,  214],
        [   0,  258],
        ...,
        [2914, 2687],
        [2914, 5997],
        [2915, 5999]], dtype=int32),
 array([0.06388766, 0.06900655, 0.03138824, ..., 0.06085806, 1.        ,
        1.        ]),
 (2916, 6000))

### for validation support...

In [177]:
if not sp.isspmatrix_coo(val_support):
    sparse_mx = val_support.tocoo()
    coords = np.vstack((sparse_mx.row, sparse_mx.col)).transpose()
    values = sparse_mx.data
    shape = sparse_mx.shape
print('sparse_mx ', sparse_mx)
print('coords' , coords)
print('values' , values)
print('shape' , shape)

sparse_mx    (0, 269)	0.11470786482095718
  (0, 1060)	0.1178511381149292
  (0, 1231)	0.22360679507255554
  (0, 2859)	0.22360679507255554
  (0, 3000)	1.0
  (1, 164)	0.05976143479347229
  (1, 300)	0.06324555724859238
  (1, 392)	0.05773502588272095
  (1, 426)	0.08451542258262634
  (1, 606)	0.15811388194561005
  (1, 709)	0.08770579844713211
  (1, 1501)	0.09128709137439728
  (1, 2080)	0.08164965361356735
  (1, 2639)	0.11180339753627777
  (1, 2763)	0.11952286958694458
  (1, 3001)	1.0
  (2, 40)	0.041522737592458725
  (2, 323)	0.0690065547823906
  (2, 390)	0.09534625709056854
  (2, 458)	0.06085806339979172
  (2, 683)	0.10000000149011612
  (2, 1562)	0.09128709137439728
  (2, 1602)	0.08451542258262634
  (2, 1640)	0.18257418274879456
  (2, 2065)	0.0690065547823906
  :	:
  (2972, 644)	0.07881104201078415
  (2972, 766)	0.15430335700511932
  (2972, 2913)	0.18898224830627441
  (2972, 5994)	1.0
  (2973, 517)	0.14433756470680237
  (2973, 656)	0.5
  (2973, 698)	0.07624928653240204
  (2973, 958)	0.144337

In [178]:
val_support=coords,values,shape

### for val_support_t

In [179]:
if not sp.isspmatrix_coo(val_support_t):
    sparse_mx = val_support_t.tocoo()
    coords = np.vstack((sparse_mx.row, sparse_mx.col)).transpose()
    values = sparse_mx.data
    shape = sparse_mx.shape
print('sparse_mx ', sparse_mx)
print('coords' , coords)
print('values' , values)
print('shape' , shape)

sparse_mx    (0, 40)	0.06388765573501587
  (0, 214)	0.06900654733181
  (0, 258)	0.031388238072395325
  (0, 296)	0.04879499971866608
  (0, 433)	0.04879499971866608
  (0, 741)	0.07559289038181305
  (0, 823)	0.04225771129131317
  (0, 885)	0.039840955287218094
  (0, 920)	0.04517539218068123
  (0, 969)	0.08451542258262634
  (0, 1067)	0.04688072204589844
  (0, 1071)	0.05096471682190895
  (0, 1160)	0.033806171268224716
  (0, 1509)	0.07559289038181305
  (0, 1544)	0.11952285468578339
  (0, 1561)	0.07559289038181305
  (0, 1608)	0.06388765573501587
  (0, 1625)	0.05096471682190895
  (0, 1899)	0.05976142734289169
  (0, 1914)	0.04225771129131317
  (0, 1923)	0.03688555210828781
  (0, 1931)	0.06900654733181
  (0, 2034)	0.038778334856033325
  (0, 2118)	0.07559289038181305
  (0, 2162)	0.023904573172330856
  :	:
  (2984, 1363)	0.22360679507255554
  (2984, 1921)	0.1154700517654419
  (2984, 2019)	0.08606629818677902
  (2984, 5996)	1.0
  (2985, 562)	0.2357022613286972
  (2985, 795)	0.14907120168209076
  (29

In [180]:
val_support_t=coords,values,shape

### for train_support...

In [185]:
if not sp.isspmatrix_coo(train_support):
    sparse_mx = train_support.tocoo()
    coords = np.vstack((sparse_mx.row, sparse_mx.col)).transpose()
    values = sparse_mx.data
    shape = sparse_mx.shape
print('sparse_mx ', sparse_mx)
print('coords' , coords)
print('values' , values)
print('shape' , shape)

sparse_mx    (0, 269)	0.11470786482095718
  (0, 1060)	0.1178511381149292
  (0, 1231)	0.22360679507255554
  (0, 2859)	0.22360679507255554
  (0, 3000)	1.0
  (1, 164)	0.05976143479347229
  (1, 300)	0.06324555724859238
  (1, 392)	0.05773502588272095
  (1, 426)	0.08451542258262634
  (1, 606)	0.15811388194561005
  (1, 709)	0.08770579844713211
  (1, 1501)	0.09128709137439728
  (1, 2080)	0.08164965361356735
  (1, 2639)	0.11180339753627777
  (1, 2763)	0.11952286958694458
  (1, 3001)	1.0
  (2, 40)	0.041522737592458725
  (2, 323)	0.0690065547823906
  (2, 390)	0.09534625709056854
  (2, 458)	0.06085806339979172
  (2, 683)	0.10000000149011612
  (2, 1562)	0.09128709137439728
  (2, 1602)	0.08451542258262634
  (2, 1640)	0.18257418274879456
  (2, 2065)	0.0690065547823906
  :	:
  (2994, 644)	0.07881104201078415
  (2994, 766)	0.15430335700511932
  (2994, 2913)	0.18898224830627441
  (2994, 5994)	1.0
  (2995, 517)	0.14433756470680237
  (2995, 656)	0.5
  (2995, 698)	0.07624928653240204
  (2995, 958)	0.144337

In [186]:
train_support=coords,values,shape

### for train_support_t...

In [187]:
if not sp.isspmatrix_coo(train_support_t):
    sparse_mx = train_support_t.tocoo()
    coords = np.vstack((sparse_mx.row, sparse_mx.col)).transpose()
    values = sparse_mx.data
    shape = sparse_mx.shape
print('sparse_mx ', sparse_mx)
print('coords' , coords)
print('values' , values)
print('shape' , shape)

sparse_mx    (0, 40)	0.06388765573501587
  (0, 214)	0.06900654733181
  (0, 258)	0.031388238072395325
  (0, 296)	0.04879499971866608
  (0, 433)	0.04879499971866608
  (0, 741)	0.07559289038181305
  (0, 823)	0.04225771129131317
  (0, 885)	0.039840955287218094
  (0, 920)	0.04517539218068123
  (0, 969)	0.08451542258262634
  (0, 1067)	0.04688072204589844
  (0, 1071)	0.05096471682190895
  (0, 1160)	0.033806171268224716
  (0, 1509)	0.07559289038181305
  (0, 1544)	0.11952285468578339
  (0, 1561)	0.07559289038181305
  (0, 1608)	0.06388765573501587
  (0, 1625)	0.05096471682190895
  (0, 1899)	0.05976142734289169
  (0, 1914)	0.04225771129131317
  (0, 1923)	0.03688555210828781
  (0, 1931)	0.06900654733181
  (0, 2034)	0.038778334856033325
  (0, 2118)	0.07559289038181305
  (0, 2162)	0.023904573172330856
  :	:
  (2996, 1363)	0.22360679507255554
  (2996, 1921)	0.1154700517654419
  (2996, 2019)	0.08606629818677902
  (2996, 5996)	1.0
  (2997, 562)	0.2357022613286972
  (2997, 795)	0.14907120168209076
  (29

In [188]:
train_support_t=coords,values,shape

### for u_features...

In [206]:
if not sp.isspmatrix_coo(u_features):
    sparse_mx = u_features.tocoo()
    coords = np.vstack((sparse_mx.row, sparse_mx.col)).transpose()
    values = sparse_mx.data
    shape = sparse_mx.shape
print('sparse_mx ', sparse_mx)
print('coords' , coords)
print('values' , values)
print('shape' , shape)

sparse_mx    (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
  (6, 6)	1.0
  (7, 7)	1.0
  (8, 8)	1.0
  (9, 9)	1.0
  (10, 10)	1.0
  (11, 11)	1.0
  (12, 12)	1.0
  (13, 13)	1.0
  (14, 14)	1.0
  (15, 15)	1.0
  (16, 16)	1.0
  (17, 17)	1.0
  (18, 18)	1.0
  (19, 19)	1.0
  (20, 20)	1.0
  (21, 21)	1.0
  (22, 22)	1.0
  (23, 23)	1.0
  (24, 24)	1.0
  :	:
  (2975, 2975)	1.0
  (2976, 2976)	1.0
  (2977, 2977)	1.0
  (2978, 2978)	1.0
  (2979, 2979)	1.0
  (2980, 2980)	1.0
  (2981, 2981)	1.0
  (2982, 2982)	1.0
  (2983, 2983)	1.0
  (2984, 2984)	1.0
  (2985, 2985)	1.0
  (2986, 2986)	1.0
  (2987, 2987)	1.0
  (2988, 2988)	1.0
  (2989, 2989)	1.0
  (2990, 2990)	1.0
  (2991, 2991)	1.0
  (2992, 2992)	1.0
  (2993, 2993)	1.0
  (2994, 2994)	1.0
  (2995, 2995)	1.0
  (2996, 2996)	1.0
  (2997, 2997)	1.0
  (2998, 2998)	1.0
  (2999, 2999)	1.0
coords [[   0    0]
 [   1    1]
 [   2    2]
 ...
 [2997 2997]
 [2998 2998]
 [2999 2999]]
values [1. 1. 1. ... 1. 1. 1.]
shape (3000, 6000)


In [207]:
u_features=coords,values,shape

In [208]:
u_features

(array([[   0,    0],
        [   1,    1],
        [   2,    2],
        ...,
        [2997, 2997],
        [2998, 2998],
        [2999, 2999]], dtype=int32),
 array([1., 1., 1., ..., 1., 1., 1.]),
 (3000, 6000))

### for v_features...

In [209]:
if not sp.isspmatrix_coo(v_features):
    sparse_mx = v_features.tocoo()
    coords = np.vstack((sparse_mx.row, sparse_mx.col)).transpose()
    values = sparse_mx.data
    shape = sparse_mx.shape
print('sparse_mx ', sparse_mx)
print('coords' , coords)
print('values' , values)
print('shape' , shape)

sparse_mx    (0, 3000)	1.0
  (1, 3001)	1.0
  (2, 3002)	1.0
  (3, 3003)	1.0
  (4, 3004)	1.0
  (5, 3005)	1.0
  (6, 3006)	1.0
  (7, 3007)	1.0
  (8, 3008)	1.0
  (9, 3009)	1.0
  (10, 3010)	1.0
  (11, 3011)	1.0
  (12, 3012)	1.0
  (13, 3013)	1.0
  (14, 3014)	1.0
  (15, 3015)	1.0
  (16, 3016)	1.0
  (17, 3017)	1.0
  (18, 3018)	1.0
  (19, 3019)	1.0
  (20, 3020)	1.0
  (21, 3021)	1.0
  (22, 3022)	1.0
  (23, 3023)	1.0
  (24, 3024)	1.0
  :	:
  (2975, 5975)	1.0
  (2976, 5976)	1.0
  (2977, 5977)	1.0
  (2978, 5978)	1.0
  (2979, 5979)	1.0
  (2980, 5980)	1.0
  (2981, 5981)	1.0
  (2982, 5982)	1.0
  (2983, 5983)	1.0
  (2984, 5984)	1.0
  (2985, 5985)	1.0
  (2986, 5986)	1.0
  (2987, 5987)	1.0
  (2988, 5988)	1.0
  (2989, 5989)	1.0
  (2990, 5990)	1.0
  (2991, 5991)	1.0
  (2992, 5992)	1.0
  (2993, 5993)	1.0
  (2994, 5994)	1.0
  (2995, 5995)	1.0
  (2996, 5996)	1.0
  (2997, 5997)	1.0
  (2998, 5998)	1.0
  (2999, 5999)	1.0
coords [[   0 3000]
 [   1 3001]
 [   2 3002]
 ...
 [2997 5997]
 [2998 5998]
 [2999 5999]]
va

In [210]:
v_features=coords,values,shape

In [211]:
v_features

(array([[   0, 3000],
        [   1, 3001],
        [   2, 3002],
        ...,
        [2997, 5997],
        [2998, 5998],
        [2999, 5999]], dtype=int32),
 array([1., 1., 1., ..., 1., 1., 1.]),
 (3000, 6000))

In [212]:
# Number of features of users and items must be the same!
assert u_features[2][1] == v_features[2][1]

In [213]:
num_features = u_features[2][1]
u_features_nonzero = u_features[1].shape[0]
v_features_nonzero = v_features[1].shape[0]

In [214]:
num_features

6000

In [215]:
u_features_nonzero

3000

In [216]:
v_features_nonzero

3000

In [32]:
u_feat = np.eye(1,num_items)

In [36]:
u_feat.reshape([-1])

array([1., 0., 0., ..., 0., 0., 0.])