In [1]:
##import libraries
import pandas as pd
import numpy as np

from sklearn.linear_model import (LinearRegression,Ridge,Lasso,HuberRegressor)
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
##step-1 load dataset
dataset = pd.read_csv("D:/US_House_Price_Pred/USA_Housing.csv")
dataset.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [7]:
roundedDataset = round(dataset.loc[:,:],ndigits=1 )

In [8]:
x = roundedDataset.loc[:,"Avg. Area Income":"Area Population"]
x.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0           79545.5                  5.7                        7.0   
1           79248.6                  6.0                        6.7   
2           61287.1                  5.9                        8.5   
3           63345.2                  7.2                        5.6   
4           59982.2                  5.0                        7.8   

   Avg. Area Number of Bedrooms  Area Population  
0                           4.1          23086.8  
1                           3.1          40173.1  
2                           5.1          36882.2  
3                           3.3          34310.2  
4                           4.2          26354.1

In [5]:
y = dataset["Price"]
y.head()

0    1.059034e+06
1    1.505891e+06
2    1.058988e+06
3    1.260617e+06
4    6.309435e+05
Name: Price, dtype: float64

In [6]:
##step-2 split dataset
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.4,random_state=3)

In [7]:
xtrain.shape,xtest.shape,x.shape

((3000, 5), (2000, 5), (5000, 5))

In [8]:
xtrain.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
2512      68201.412486             4.196948                   5.969959   
597       64823.015835             5.079006                   7.053927   
3091      46367.205859             5.290720                   5.181614   
4830      55468.486886             6.783951                   7.798628   
493       62566.562637             4.937435                   6.346328   

      Avg. Area Number of Bedrooms  Area Population  
2512                          2.30     43468.164465  
597                           5.12     36481.327752  
3091                          4.50     26015.296447  
4830                          3.40     37666.331185  
493                           2.41     29365.607608

In [9]:
##step-3 define an algorithm
model1 = LinearRegression()
model2 = Ridge()
model3 = Lasso()
model4 = HuberRegressor()

In [10]:
##step-4 Training 
model1.fit(xtrain,ytrain)

LinearRegression()

In [11]:
model2.fit(xtrain,ytrain)

Ridge()

In [12]:
model3.fit(xtrain,ytrain)

Lasso()

In [13]:
model4.fit(xtrain,ytrain)

HuberRegressor()

In [14]:
##step-5 and step-6 skipping for now...

In [15]:
##step-7 cross validation for model 1 (linear regression)
ypred1 = model1.predict(xtest)
ypred1

array([1262721.89209657, 1497473.65051982, 1563168.24058248, ...,
       1409653.3207282 ,  906014.98617218, 1308471.15437722])

In [16]:
ytest

2584    1.122083e+06
4338    1.565152e+06
4556    1.603075e+06
3438    1.104116e+06
737     1.442129e+06
            ...     
3812    8.840152e+05
2816    1.539085e+06
2491    1.431517e+06
3363    8.908877e+05
2352    1.358983e+06
Name: Price, Length: 2000, dtype: float64

In [17]:
error1 = np.sqrt(mean_squared_error(ypred1,ytest))
error1

102286.8055354031

In [18]:
model1.predict([[1000,1000,250,250,250]])

array([1.94855649e+08])

In [19]:
##model 2 (Ridge)
ypred2 = model2.predict(xtest)
ypred2

array([1262769.6091313 , 1497353.8917814 , 1563203.66306151, ...,
       1409622.71587283,  906070.08924859, 1308550.74430106])

In [20]:
error2 = np.sqrt(mean_squared_error(ypred2, ytest))
error2

102284.44756899243

In [21]:
model2.predict([[1000,1000,250,250,250]])

array([1.94791901e+08])

In [23]:
##model 3 (Lasso)
ypred3 = model3.predict(xtest)
ypred3

array([1262722.4686708 , 1497472.11330824, 1563168.61881137, ...,
       1409651.96981058,  906016.5253657 , 1308472.2323728 ])

In [24]:
error3 = np.sqrt(mean_squared_error(ypred3,ytest))
error3

102286.72071961843

In [25]:
model3.predict([[1000,1000,250,250,250]])

array([1.94854366e+08])

In [26]:
##model 4 (huber regressor)
ypred4 = model4.predict(xtest)
ypred4

array([1350317.36143755, 1233288.25212089, 1485959.70566753, ...,
       1274642.69923687, 1141441.67094882, 1400726.23323893])

In [28]:
error4 = np.sqrt(mean_squared_error(ypred4,ytest))
error4

250257.2273627124

In [29]:
model4.predict([[1000,1000,250,250,250]])

array([15378.29721695])

In [43]:
import pickle as pk

In [44]:
##Linear Regression
fileName1 = "US-House-Prediction-using-linear-regression.pkl"

In [45]:
pk.dump(model1,open(fileName1,'wb'))

In [50]:
loadedDataset1 = pk.load(open(fileName1,'rb'))
loadedDataset1

LinearRegression()

In [51]:
loadedDataset1.predict([[1000,1000,250,250,250]])

array([1.94855649e+08])

In [52]:
##Ridge Regression
fileName2 = "US-House-Prediction-using-RIDGE.pkl"

In [53]:
pk.dump(model2,open(fileName2,'wb'))

In [54]:
loadedDataset2 = pk.load(open(fileName2,'rb'))
loadedDataset2

Ridge()

In [55]:
loadedDataset2.predict([[1000.,1000,250,250,250]])

array([1.94791901e+08])

In [56]:
##Lasso Regression
fileName3 = "US-House-Prediction-using-LASSO.pkl"

In [57]:
pk.dump(model3,open(fileName3,'wb'))

In [58]:
loadedDataset3 = pk.load(open(fileName3,'rb'))
loadedDataset3

Lasso()

In [59]:
loadedDataset3.predict([[1000,1000,250,250,250]])

array([1.94854366e+08])

In [60]:
## Huber Regression
fileName4 = "US-House-Prediction-using-huber.pkl"

In [61]:
pk.dump(model4,open(fileName4,'wb'))

In [63]:
loadedDataset4 = pk.load(open(fileName4,'rb'))
loadedDataset4

HuberRegressor()

In [64]:
loadedDataset4.predict([[1000,1000,250,250,250]])

array([15378.29721695])